[#ISSUE 1005] - Expand checkstyle to all modules (root).
apache/shiro pull request #1069
Opened 2023-09-10 14:58 UTC by damonxue

fixes #1005 

If your pull request is about ~20 lines of code you don't need to sign an [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) 
I had signed an [Individual Contributor License Agreement] in `Apache ShenYu` project.

2023-09-10 14:59 UTC, damonxue commented
#1059

2023-09-12 10:17 UTC, damonxue commented
* The reason for formatting too many files is to make sure that they all end with 'lf'. 
   > I rolled back *.md, *.yml and others not need formatted.
* I will change too many 'lineLength'.

@lprimak @bmarwell pls review.

2023-10-03 21:05 UTC, lprimak commented
I have started the review process. So far it looks great!

2023-10-04 02:34 UTC, lprimak commented
One comment:
You are still trying to do **way** too much. I will fix it up, but you are just creating extra work for the reviewers unnecessarily.

2023-10-04 03:01 UTC, lprimak commented
Also, please do not close this PR and open another one, or make more massive changes. I can't devote 5+ hours to start from the beginning again.

Thank you!

Overall, great job, we are close to merge.

2023-10-04 05:51 UTC, fpapon requested changes
@damonxue can you squash the commits and rebase from main?

2023-10-04 05:52 UTC, fpapon commented
@damonxue thank you for the great work!

2023-10-04 05:54 UTC, lprimak commented
@damonxue please don't squash the commit just yet. I will let you know. I am not done with my review / changes.
Once I am done, I will let you know, or maybe do it myself :)

2023-10-04 07:23 UTC, lprimak commented
@damonxue I am done with my changes. Feel free to squash the commits, or let me know if you want me to do it.
Either way is fine with me.

2023-10-04 07:38 UTC, lprimak approved these changes
Looks great!

2023-10-05 01:50 UTC, lprimak commented
I have rebased & squashed the commits.  Should be good to go tomorrow :)

2023-10-05 17:44 UTC, merged