[#SHIRO-875] Fix creating subjects from a `SubjectFactory` that disables session-creation
apache/shiro pull request #1514
Opened 2024-05-31 17:46 UTC by boris-petrov

I'm not sure if I had to remove the PR template after I've read it and made sure I followed everything in it. Perhaps you might want to note that in it.

This continues the work done in #1407. I didn't think of that case in it so this PR fixes it. I didn't open a new issue for it, sorry, I guess we could reuse the old one as it's a similar case.

cc @lprimak

2024-06-02 03:33 UTC, lprimak approved these changes

2024-06-03 18:07 UTC, bdemers requested changes
This change looks good, but the test doesn't look like it's asserting that no session is being created?  Can the test be improved (or commented if i'm reading it wrong)

2024-06-03 18:10 UTC, boris-petrov commented
@bdemers thanks for the feedback! The test is pretty much the same as the one above it - it doesn't do anything with the session on its own but the `buildSubject` call fails without the fix (as it calls `save` which tries creating a session). I could add a comment, sure.

2024-06-03 20:53 UTC, fpapon approved these changes
@boris-petrov thanks for your contribution!

2024-06-03 21:32 UTC, merged