Issue #1499: Deleted Quartz module.
apache/shiro pull request #1581
Opened 2024-07-10 09:54 UTC by Himakar

Fixed Issue #1499: Quartz module deletion
The module was present in shiro\support folder

2024-07-10 14:24 UTC, bdemers commented
Note: We need to wait until we cut the 3.x branch before merging this (but we can get it ready to go!).

My pref would be to hold off creating the branch until we have a few PRs lined up that depend on each (as to avoid any additional back porting), but... avoiding backporting might just be a dream 😆
(I'm also not trying to block anyone from cutting the 3.x branch if they are motivated) 😄

2024-07-10 15:47 UTC, lprimak commented
Yea, I think not having 3.x branch is starting to block things...

2024-07-10 15:48 UTC, lprimak commented
@Himakar Can you fix the failing build please? I think it's just a matter of removing quartz from the coverage module

2024-07-11 17:23 UTC, lprimak commented on test-coverage/pom.xml
> -
Please restore this whitespace. (I know... nit :)

2024-07-11 17:23 UTC, lprimak requested changes
Please restore the issue template. We need that for you to accept Apache CLA license agreement

2024-07-11 17:24 UTC, lprimak commented
Also, please squash the commits into one.
Otherwise, LGTM, thank you!

2024-07-26 20:25 UTC, lprimak commented
@Himakar Can you please fix the remaining issues as described above please?
Thank you!

2024-08-04 02:31 UTC, lprimak commented
@Himakar Any updates please?
We have created 3.x branch and can merge this if you make the necessary changes.
Thank you!

2024-08-06 00:48 UTC, lprimak commented
@Himakar Last thing you have to do is to click the CLA checkbox(es) and squash the commits.
Do you know how to do that?

2024-08-07 10:09 UTC, Himakar commented
Hi @lprimak, Could you please let me know hint on CLA checkboxes and squash part

2024-08-08 03:03 UTC, lprimak commented
1. Just read the PR description. There are checkboxes there about license agreement. Read and click on the appropriate checkboxes.
2. See https://stackoverflow.com/questions/5189560/how-do-i-squash-my-last-n-commits-together

2024-08-08 22:22 UTC, lprimak commented
No problem! Somehow your squashed changes didn't "take" on this PR. Please don't create new PRs, and use this PR.
Please try squashing / force-push this PR again.

2024-08-08 22:23 UTC, lprimak commented
Also, I based this branch of the 3.x branch now, please make a note of that.

2024-08-14 18:12 UTC, lprimak commented
@Himakar Any updates? We are so close :)

2024-08-15 14:48 UTC, Himakar commented
Hi @lprimak ,
I can see the commit items in the pull request. Am i missing something else?

![image](https://github.com/user-attachments/assets/0c9970f3-beaf-4f46-8bd9-2f50f12562d1)

2024-08-15 19:15 UTC, lprimak commented
Your screenshot points to the *closed* PR. You need to squash commits on **this** PR. It still shows 7 commits.

Also, now there is a conflict that needs to be fixed

2024-08-16 06:35 UTC, fpapon commented
@Himakar I think you need to rebase your PR.

2024-08-16 13:42 UTC, fpapon commented
@Himakar you are rebasing from `main` rather than `3.x` branch, this is why you added more recent commit from main.
You need to be sync to `3.x` branch and not `main`.

2024-08-16 16:03 UTC, Himakar commented
Hi @fpapon, Thanks for your help. Now i have rebased my branch from 3.x branch and pushed code.
Is this fine now?

2024-08-16 16:11 UTC, fpapon commented
The 4 commits from dependabot are from main and not from 3.x.
You can remove them with `git rebase -i HEAD~5` and drop them.

2024-08-16 16:26 UTC, fpapon approved these changes
Thanks for your contribution!

2024-08-16 16:27 UTC, merged

2024-08-17 01:32 UTC, Himakar commented
Hi @lprimak , @fpapon ,
Thank you for your help. It means a lot to me. 
I am learning new concepts because of this task.
Thank you once again

2024-08-17 01:43 UTC, lprimak commented
Awesome!  We are happy to help. Thanks and keep it up!

2024-08-19 06:46 UTC, fpapon commented
@Himakar you're welcome and don't hesitate to make other proposal!