hotfix Shiro 1.7.0 is lower than using springboot version 2.0.7 dependency error
apache/shiro pull request #263
Opened 2020-11-04 16:23 UTC by dngzs

hotfix Springboot in versions lower than 2.0.7 does not have trim classname, one more space causes an error

https://issues.apache.org/jira/projects/SHIRO/issues/SHIRO-797?filter=allopenissues

2020-11-10 06:56 UTC, fpapon requested changes
License header is missing in test classes.
@bdemers can you add them?

2020-11-10 14:40 UTC, bdemers commented
> License header is missing in test classes.
> @bdemers can you add them?

🤦 on it

2020-11-10 16:08 UTC, fpapon approved these changes
@bdemers all good :+1:

2020-11-10 16:09 UTC, merged

2020-11-16 02:07 UTC, tonypig93 commented
@fpapon so when will we get a new release for this issue?

2020-11-16 07:49 UTC, fpapon commented
@tonypig93 I will check the 1.7.1 on Jira to see when we can cut the release.