Pr template
apache/shiro pull request #279
Opened 2021-01-13 10:30 UTC by Palak-137

According to the issue on Jira the pull_request_template.md needs to be updated.
So I added the guideline to add -Purn-its to activate profile test.

2021-01-13 10:55 UTC, fpapon requested changes
@Palak-137 please provide a PR with only the template changes commit

2021-01-13 11:21 UTC, Palak-137 commented
Yes i have revert the rest of changes.

2021-01-13 12:40 UTC, fpapon reviewed
the best way is to drop the commits with `git rebase -i HEAD~8`

2021-01-13 13:23 UTC, bmarwell commented on lang/src/main/java/org/apache/shiro/lang/io/ClassResolvingObjectInputStream.java
> - * Enables correct ClassLoader lookup in various environments (e.g. JEE Servers, etc).
This file must not be part of the commit. Please rebase and create the PR from a branch.

2021-01-13 13:24 UTC, bmarwell requested changes
Prepend `[SHIRO-802]` for the PR and for each commit which has todo with this issue (after rebasing, please edit your commit)

2021-01-13 20:58 UTC, fpapon approved these changes
LGTM
@Palak-137 thanks!

2021-01-14 07:13 UTC, bmarwell requested changes
typo

2021-01-14 07:13 UTC, bmarwell commented on .github/pull_request_template.md
> + - [ ] By default the project packages the tests in an artifact. To activate them Run `mvn clean test -Purn-its`.
typo: `run-its`, not `urn-its`.

2021-01-14 08:15 UTC, bmarwell requested changes

2021-01-14 08:15 UTC, bmarwell commented on .github/pull_request_template.md
> + - [ ] By default the project packages the tests in an artifact. To activate them,activate the `run-its` profile:  `mvn clean test -Purn-its`.
1. Still "urn-its".
2. test will not run its. You will need "clean verify".
3. nit: Please add a space after a comma (between "them,activate").

2021-01-14 08:16 UTC, bmarwell commented on .github/pull_request_template.md
> + - [ ] By default the project packages the tests in an artifact. To activate them,activate the `run-its` profile:  `mvn clean test -Purn-its`.
Proposed: "to activate them, run `mvn clean test -Prun-its`.

2021-02-19 12:35 UTC, fpapon commented
@Palak-137 can you squash the commits please?

2021-02-20 12:24 UTC, closed without merging